# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class LineNode(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, inputs=None):  # noqa: E501
        """LineNode - a model defined in OpenAPI

        :param name: The name of this LineNode.  # noqa: E501
        :type name: str
        :param inputs: The inputs of this LineNode.  # noqa: E501
        :type inputs: object
        """
        self.openapi_types = {
            'name': str,
            'inputs': object
        }

        self.attribute_map = {
            'name': 'name',
            'inputs': 'inputs'
        }

        self._name = name
        self._inputs = inputs

    @classmethod
    def from_dict(cls, dikt) -> 'LineNode':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The lineNode of this LineNode.  # noqa: E501
        :rtype: LineNode
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this LineNode.


        :return: The name of this LineNode.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LineNode.


        :param name: The name of this LineNode.
        :type name: str
        """

        self._name = name

    @property
    def inputs(self):
        """Gets the inputs of this LineNode.


        :return: The inputs of this LineNode.
        :rtype: object
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this LineNode.


        :param inputs: The inputs of this LineNode.
        :type inputs: object
        """

        self._inputs = inputs
