# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Node(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id:int = None, name:str = None, position:int = None, inputs:object = None):  # noqa: E501
        """Node - a model defined in OpenAPI

        :param id: The id of this Node.  # noqa: E501
        :type id: int
        :param name: The name of this Node.  # noqa: E501
        :type name: str
        :param position: The position of this Node.  # noqa: E501
        :type position: int
        :param inputs: The inputs of this Node.  # noqa: E501
        :type inputs: object
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'position': int,
            'inputs': object
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'position': 'position',
            'inputs': 'inputs'
        }

        self._id = id
        self._name = name
        self._position = position
        self._inputs = inputs

    @classmethod
    def from_dict(cls, dikt) -> 'Node':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Node of this Node.  # noqa: E501
        :rtype: Node
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Node.

        ID of Node  # noqa: E501

        :return: The id of this Node.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Node.

        ID of Node  # noqa: E501

        :param id: The id of this Node.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Node.

        Name of the implemented function  # noqa: E501

        :return: The name of this Node.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Node.

        Name of the implemented function  # noqa: E501

        :param name: The name of this Node.
        :type name: str
        """

        self._name = name

    @property
    def position(self):
        """Gets the position of this Node.

        Position of node in line  # noqa: E501

        :return: The position of this Node.
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this Node.

        Position of node in line  # noqa: E501

        :param position: The position of this Node.
        :type position: int
        """

        self._position = position

    @property
    def inputs(self):
        """Gets the inputs of this Node.

        Input key-value pairs as object  # noqa: E501

        :return: The inputs of this Node.
        :rtype: object
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this Node.

        Input key-value pairs as object  # noqa: E501

        :param inputs: The inputs of this Node.
        :type inputs: object
        """

        self._inputs = inputs
