// tslint:disable
/**
 * Vision Line API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface FunctionInput
 */
export interface FunctionInput {
    /**
     * @type {string}
     * @memberof FunctionInput
     */
    name?: string;
    /**
     * @type {string}
     * @memberof FunctionInput
     */
    display?: string;
    /**
     * @type {string}
     * @memberof FunctionInput
     */
    type?: string;
    /**
     * @type {Array<object>}
     * @memberof FunctionInput
     */
    values?: Array<object>;
    /**
     * @type {string}
     * @memberof FunctionInput
     */
    regex?: string;
}
