openapi: '3.0.2'
info:
  title: Vision Line API
  version: '1.0'
servers:
  - url: http://localhost:5000/api/v1/
  
paths:
  /createImage:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lineNodeList'
      responses:
        200:
          description: OK
  /createImage/{lineId}/add/{position}:
    post:
      parameters:
        - in: path
          name: lineId
          schema:
            type: integer
          required: true
        - in: path
          name: position
          schema:
            type: integer
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lineNode'
      responses:
        200:
          description: OK
  /createImage/{lineId}/delete/{position}:
    delete:
      parameters:
        - in: path
          name: lineId
          schema:
            type: integer
          required: true
        - in: path
          name: position
          schema:
            type: integer
          required: true
      responses:
        200:
          description: OK

  /functions:
    get:
      description: Get all possible functions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Function"
  /lines:
    get:
      description: Get current lines
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Line"
    post:
      description: Create new line
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Line"        
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Node"



components:
  schemas:
    lineNode:
      type: object
      properties:
        name:
          type: string
        inputs:
          type: object
          nullable: true
    lineNodeList:
      type: array
      items:
        $ref: "#/components/schemas/lineNode"

    FunctionInput:
      type: object
      properties:
        name:
          type: string
        display:
          type: string
        type:
          type: string
    Function:
      type: object
      properties:
        name: 
          type: string
        inputs:
          type: array
          items:
            $ref: "#/components/schemas/FunctionInput"
      example: {name: 'blur', inputs: [{name: 'kernel', type: 'int'}]}
    Node:
      type: object
      properties:
        name:
          type: string
          description: Name of the implemented function
        inputs:
          type: object
          description: Input key-value pairs as object
    Line:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        nodes:
          type: integer
          description: Count of nodes
        lastChange:
          type: number
          description: Epoch of last modification
      